### ISSUE TITLE
View List Project Font-End

### ISSUE THREAD

**Issue by KhaMinhVLU-2017** [KhaMinhVLU-2017/PPCRental_2017#3]
Xem danh sách dự án của người dùng trên website

Lưu ý: các bạn có thể commit thoải máy. Nhưng khi complete task của mình rồi thì commit cuối cùng là số thư tự công việc của mình.
Vd: KhaMinhVLU-2017
Task: View Detail Project
Thứ tự task là : #1
=>> commit cuối cùng của bạn ấy phải là #1 để done task.
Chúc các bạn có một khoãng thời gian làm việc vui vẽ...!

**Comment by TranAnhPhuongbl1997** [comment]
Done
